(custom-set-faces
  ;; custom-set-faces was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(paren-face-match ((((class color)) (:background "green"))))
 '(paren-face-mismatch ((((class color)) (:foreground "white" :background "red"))))
 '(paren-match ((t (:background "green"))))
 '(paren-mismatch ((t (:background "red"))))
 '(show-paren-match-face ((((class color)) (:background "green"))))
 '(show-paren-mismatch-face ((((class color)) (:background "red"))))
 '(variable-pitch ((t (:family "helvetica")))))
(custom-set-variables
  ;; custom-set-variables was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(add-log-mailing-address nil t)
 '(bbdb-north-american-phone-numbers-p nil)
 '(browse-url-browser-function (quote w3m-browse-url) t)
 '(browse-url-galeon-arguments (quote ("-n")))
 '(bsh-jar "/usr/share/java/bsh.jar")
 '(canlock-password "165523ce79fcd63dfb5b422d9a24488b238bef98")
 '(confirm-kill-emacs (quote y-or-n-p))
 '(debian-bug-always-CC-myself nil)
 '(debian-bug-helper-program (quote reportbug))
 '(debian-changelog-mailing-address "rotty@debian.org")
 '(dictionary-server "dict")
 '(ecb-layout-name "rotty-01")
 '(ecb-layout-nr 7)
 '(enable-multibyte-characters t)
 '(enable-recursive-minibuffers t)
 '(european-calendar-style nil t)
 '(exec-path (quote ("/home/andy/bin" "/home/andy/.system/bin" "/usr/local/bin" "/usr/bin" "/bin" "/usr/bin/X11" "/usr/games" "/usr/lib/emacs/21.3/i386-linux")))
 '(general-holidays nil t)
 '(glasses-face (quote bold))
 '(glasses-separator "")
 '(global-font-lock-mode t nil (font-lock))
 '(gnus-summary-mark-below -100)
 '(gnuserv-frame nil)
 '(ispell-local-dictionary "german-new8")
 '(jde-compiler (quote ("javac" "")))
 '(log-edit-confirm t)
 '(mail-source-delete-incoming t)
 '(mail-source-directory "~/mail/")
 '(mail-sources (quote ((directory :path "~/var/mail/incoming/" :suffix ".spool"))))
 '(max-lisp-eval-depth 20000)
 '(max-specpdl-size 100040)
 '(message-log-max 1000)
 '(message-user-fqdn "ivanova.rotty.yi.org")
 '(message-wide-reply-to-function (quote my-message-wide-reply-to-function))
 '(paren-mode (quote paren) nil (paren))
 '(quack-global-menu-p nil)
 '(quack-pltish-keywords-to-fontify (quote ("and" "begin" "call-with-current-continuation" "call-with-input-file" "call-with-output-file" "call/cc" "case" "case-lambda" "compound-unit/sig" "cond" "condition" "cond-expand" "define" "define*" "define-condition-type" "define-macro" "define-module" "define-public" "define-signature" "define-syntax" "define-syntax-set" "define-values" "define-values/invoke-unit/sig" "define-method" "define-generic" "define-class" "delay" "do" "else" "exit-handler" "guard" "if" "import" "lambda" "let" "let*" "let*-values" "let+" "let-keywords" "let-optional" "let-syntax" "let-values" "let/ec" "letrec" "letrec-values" "letrec-syntax" "match-lambda" "match-lambda*" "match-let" "match-let*" "match-letrec" "match-define" "mixin" "opt-lambda" "or" "override" "override*" "namespace-variable-bind/invoke-unit/sig" "parameterize" "private" "private*" "protect" "provide" "provide-signature-elements" "provide/contract" "public" "public*" "quote" "receive" "rename" "require" "require-for-syntax" "send" "send*" "setter" "set!" "set!-values" "signature->symbols" "super-instantiate" "syntax-case" "syntax-case*" "syntax-error" "syntax-rules" "unit/sig" "unless" "when" "with-handlers" "with-method" "with-syntax")))
 '(quack-programs (quote ("~/bin/scheme42" "scheme42" "light-scheme42" "~/src/contrib/s42/light-scheme42" "bigloo" "csi" "csi -hygienic" "gosh" "gsi" "gsi ~~/syntax-case.scm -" "guile" "ischeme48" "kali" "kawa" "mit-scheme" "mred -z" "mzscheme" "mzscheme -M errortrace" "rs" "schem348" "schem48" "scheme" "scheme48" "scheme48 -cl ~/src/contrib/scheme48/src/scheme48/scheme/ffi/packages.scm -cl ~/src/contrib/g-wrap/=build/scheme48/g-wrap/gw/packages.scm -o g-wrap.gw.standard" "scheme48 -cl ~/src/contrib/scheme48/src/scheme48/scheme/ffi/packages.scm -o ffi" "scheme48 -cl ~/src/foreign/sunterlib-0.7/s48/exceptions/packages.scm -cl ~/src/contrib/tiny-clos/packages.scm -o tiny-goops -o tiny-test" "scheme48 -cl ~/src/foreign/sunterlib-0.7/s48/exceptions/packages.scm -cl ~/src/contrib/tiny-clos/src/packages.scm -o tiny-goops" "scheme48 -cl ~/src/foreign/sunterlib-0.7/s48/exceptions/packages.scm -cl ~/src/contrib/tiny-clos/src/packages.scm -o tiny-goops -o tiny-test" "scheme48 -h 10000000" "scheme48 -h 100000000" "scheme48vm" "scsh" "sisc" "stklos" "sxi" "~/src/contrib/s42/heavy-scheme42" "~/src/contrib/s42/run" "~/src/contrib/s42/run-scheme42" "~/src/contrib/scheme48/svn-gw/netapi/go")))
 '(quack-remap-find-file-bindings-p nil)
 '(sh-basic-offset 2)
 '(show-paren-delay 0)
 '(show-paren-mode (quote paren) nil (paren))
 '(tool-bar-mode nil nil (tool-bar))
 '(tramp-default-method "fcp")
 '(truncate-partial-width-windows nil)
 '(user-mail-address "a.rottmann@gmx.at"))